version: '2'
services:
  explorer:
    image: makevoid/explorer
    stdin_open: true
    tty: true
    build:
      context: .
    ports:
    - 3100:3000/tcp
    environment:
      - DOCKER=1
      - BITCOIN_RPCPASS=$BITCOIN_RPCPASS
      - SENTRY_SECRET=$SENTRY_SECRET
    depends_on:
     - redis
  redis:
    image: redis
