version: '2'
services:
  explorer:
    image: makevoid/explorer
    stdin_open: true
    tty: true
    build:
      context: .
    ports:
    - 3100:3000/tcp
    environment:
      - BITCOIN_RPCPASS=$BITCOIN_RPCPASS
    labels:
      io.rancher.container.pull_image: always
    depends_on:
     - redis
  redis:
    image: redis
  explorer-lb:
    image: rancher/lb-service-haproxy:v0.7.15
    ports:
    - 3101:3101/tcp
    labels:
      io.rancher.container.agent.role: environmentAdmin,agent
      io.rancher.container.agent_service.drain_provider: 'true'
      io.rancher.container.create_agent: 'true'
#
#
# version: '2'
# services:
#   web:
#     build: .
#     ports:
#      - "4567:4567"
#     volumes:
#      - .:/app
#     depends_on:
#      - redis
#   redis:
#     image: redis

# to run this:
#
#   # (alias)
#
#   alias dc=docker-compose
#
#   # run
#
#   dc build && dc up
#
##
